### ISSUE TITLE
Remove SolvingMicroDSOPs

### ISSUE THREAD

**Issue by Mv77** [econ-ark/REMARK#141]
@MridulS @camriddell
SolvingMicroDSOPs was moved to [a standalone repo](https://github.com/econ-ark/SolvingMicroDSOPs) some time ago, but it is still in this repo as a folder, causing confusion.

It should be removed from here, but making sure that all the links in the econ-ark website and metadata files point to the new repo.

**Comment by camriddell** [comment]
Closed by #142
