### ISSUE TITLE
Align BlanchardPA2019 to standards

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/REMARK#25]
See  #23

**Comment by sbenthall** [comment]
- [x] do_all.sh to .py
- [x] metadata: .md, .bib
- [x]  Jupyter notebook
- [x] Jupytext used in do_all
- [ ] figures into Figures/ directory
- [ ] environment setup files/scripts

See #23

**Comment by sbenthall** [comment]
This is waiting on a determination of how to direct users to install individual REMARK dependencies.

This REMARK has a `binder/` directory.

If we standardize on REMARKs having a `binder/` directory, then whatever means we decide on for dependency installation should be general across all REMARKs and not specific to this one.

**Comment by llorracc** [comment]
@MridulS could you add this to the things you review?

**Comment by MridulS** [comment]
https://github.com/econ-ark/BlanchardPA2019
