### ISSUE TITLE
Simple template REMARK

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/REMARK#26]
A minimal REMARK for use as a template.

**Comment by sbenthall** [comment]
Branch for this is now here:

https://github.com/econ-ark/REMARK/tree/i26-template

Missing:
- [ ] Use of the Figures/ directory
- [ ] Modeling how to have REMARK specific dependencies
- [ ] Use of a general `remark.py` module

**Comment by sbenthall** [comment]
These three issues are linked.
In the current model `remark.py` is what puts the figures in the Figures directory, but the location of this module is in question because of `/binder` issues.

See also:
https://github.com/econ-ark/REMARK/issues/25#issuecomment-554080509
https://github.com/econ-ark/REMARK/issues/23#issuecomment-554099108

**Comment by sbenthall** [comment]
See also #41, #40, #37 ....

**Comment by MridulS** [comment]
https://github.com/econ-ark/REMARK-template
