### ISSUE TITLE
Clean up SolvingMicroDSOPs REMARK

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/REMARK#30]
The `SolvingMicroDSOPs` REMARK seems to both:
 * A `Code/StructEstimation.py` and a `Calibration/EstimationParameters.py`
 * Optional (in a `try:` block) `import`s of the corresponding code from HARK, i.e:

https://github.com/econ-ark/REMARK/blob/master/REMARKs/SolvingMicroDSOPs/do_all.py#L68

and...

https://github.com/econ-ark/REMARK/blob/master/REMARKs/SolvingMicroDSOPs/Code/StructEstimation.py#L44

From here, it looks like the imports from HARK are redundant, creating an unnecessary dependence on HARK, and should be removed. @llorracc is that correct?

This relates to [HARK #440](https://github.com/econ-ark/HARK/issues/440). `SolvingMicroDSOPs` is an application of HARK that could be moved into an `example/`, or could exist as a `REMARK`, but maybe should not be both.

If there is some aspect of the `SolvingMicroDSOPs` application that is especially reproducible, I would argue this should be split out into a _library_ classes and methods.

**Comment by llorracc** [comment]
I agree that it should not be both a REMARK and an example.  If it were shorter and simpler it would be better as an example, but given its complexity probably it is better as a REMARK.

I'm not sure there is anything that can really be turned into a reusable standalone library.  

It's quite possible that there are redundant HARK imports -- please look into that and make a PR to clean that up after verifying that you are right.  

The other thing that needs to be done with it is to create a Jupyter notebook version that can be used as a teaching tool.  Could you put that on your to-do list?

**Comment by sbenthall** [comment]
> The other thing that needs to be done with it is to create a Jupyter notebook version that can be used as a teaching tool. Could you put that on your to-do list?

OK. I think you're saying that the notebook version of this should also be in REMARKs.
I.e., this needs to be brought up to minimal REMARK standards of having a notebook.

I'll work on that. It will also be a good test case for a validation script #41

**Comment by sbenthall** [comment]
Superceded by #103
