### ISSUE TITLE
Release cycle and dependency management: design and documentation

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/REMARK#56]
Some questions have been raise about REMARK release cycle and dependency management.
This is a ticket to get clarity on those issues and document them.

This is my proposal:
 - REMARKs are analogous to publications.
 - As static artifacts, their dependencies should be locked to specific versions. (This includes HARK)
 - They may be locked to _different_ versions.
 - REMARKs should have release numbers, because their authors might want to go back and change them.

My understanding is that there is an obstacle to this proposal:
 - Most of the REMARKs are not yet "completed", or in a "publishable" form

As a consequence of the latter issue, the REMARK repository is currently being developed in an ad hoc way, with no releases or dependency locking at all.

**Comment by llorracc** [comment]
That sounds about right to me.

**Comment by sbenthall** [comment]
It looks like REMARKs are developed, controlled, and maintained by their team of authors.
That squares with the fact that they can be submodules.

Is the use of submodules in REMARKs here to stay?

The submodule link can be pointed to a specific branch. This seems to be the only supported way to link to a "stable" version of a submodule repository:
https://medium.com/faun/git-submodule-cheatsheet-29a3bfe443c3
https://github.com/econ-ark/REMARK/blob/master/.gitmodules#L12

**Comment by sbenthall** [comment]
The individual `binder/` directories seem to cover the issue of locking dependencies.
It's just a matter of putting the dependency pegs in.

Having REMARKs have individualized release numbers is more difficult because they are all in one repository.
Normally, everything in a repository is released together.

A different way to do this would be if REMARKs were _all_ in their own repositories, and then rather than be submodules, this REMARK repository could have Docker container configurations that each knew the location and latest release of the REMARKs.

**Comment by MridulS** [comment]
we should definitely make the binder/ subdirectory a requirement for all REMARKs, which has a versioned requirements.txt file, not just for HARK but numpy/scipy/ all the other dependencies required to run that REMARK. For example for the TFI blog post REMARK, I have pinned it to 0.10.5 using the configurator.py. I will also add a binder/requirements.txt file.

> Is the use of submodules in REMARKs here to stay?

We have had multiple conversations regarding this and I think we should take a clear stand regarding this, there are some REMARKs which are like a folder and some are submodules. 

There is another "naive" way of controlling this, we can just a link in a markdown file to the actual repository in the REMARKs if it's a different repository. For example BufferStockTheory is a submodule which is hosted at llorracc/BufferStockTheory, we can update the markdown file BufferStockTheory.md and move it to REMARKs/BufferStockTheory/BufferStockTheory.md with a normal link to https://github.com/llorracc/BufferStockTheory/ , this effectively decouples econ-ark/REMARK with all the other REMARKs with respect to submodules while still maintaining an index of all REMARKs. This will be much more new user friendly, and people without much experience with git will be able to keep contributing to this REMARK index without worrying about submodules.

If there are some REMARKs where it doesn't make sense to keep them in an individual repository we can follow the current way of doing it, where the REMARK lives inside the REMARKs folder.

[This will also raise the question of effectively maintaining the binder images, submodules allows us to have a meta-binder image and we can run all the remarks through econ-ark/remark]

**Comment by llorracc** [comment]
@MridulS make sure we have a checklist for REMARK releases, and then either close this or mark the REMARK parts as done.

**Comment by MridulS** [comment]
This has been largely streamlined with a starter template available at https://github.com/econ-ark/REMARK-starter-example and https://github.com/econ-ark/REMARK as the index. Documentation part needs to be added to the REAMDE (https://github.com/econ-ark/REMARK/issues/86)
