### ISSUE TITLE
We need a way to designate SOME files for SOME REMARKs as things to test on a regular basis

### ISSUE THREAD

**Issue by llorracc** [econ-ark/REMARK#78]
Don't want to test "do_all" very often, but "do_min" could perhaps be tested every week or two?

**Comment by MridulS** [comment]
`test` could be part of the REMARK metadata.

**Comment by llorracc** [comment]
This is something we should do after we have pinned all the repos to a version of HARK and after we have the redesigned website up and running

**Comment by sbenthall** [comment]
Once the REMARKs have dependencies pinned and are tied to releases, they should not need repeated testing. Closing this as a no-op.
